if(location.protocol==='file:')location.replace('http://localhost:4173/');
const u=(id)=>`https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=700&q=82`;
let products={
  Burger:[
    {image:u('1568901346375-23c9450c58cd'),name:'Cheeseburger with Salad',price:18,rating:4.9},{image:u('1550547660-d9450f859349'),name:'Classic Beef Burger',price:15,rating:4.8},{image:u('1550317138-10000687a72b'),name:'Royal Cheeseburger',price:16,rating:4.7},{image:u('1571091718767-18b5b1457add'),name:'Black Angus Burger',price:14,rating:4.8},{image:u('1586816001966-79b736744398'),name:'Crispy Chicken Burger',price:15,rating:4.9}],
  Pizza:[
    {image:u('1574071318508-1cdbab80d002'),name:'Margherita Pizza',price:16,rating:4.9},{image:u('1628840042765-356cda07504e'),name:'Pepperoni Feast',price:19,rating:4.8},{image:u('1594007654729-407eedc4be65'),name:'Garden Supreme',price:17,rating:4.7},{image:u('1565299624946-b28f40a0ae38'),name:'Cheese Volcano',price:18,rating:4.8},{image:u('1579751626657-72bc17010498'),name:'Chicken Deluxe',price:20,rating:4.9}],
  Sandwich:[
    {image:u('1553909489-cd47e0907980'),name:'Classic Club Sandwich',price:12,rating:4.7},{image:u('1528735602780-2552fd46c7af'),name:'Double Stack Sandwich',price:14,rating:4.8},{image:u('1509722747041-616f39b57569'),name:'Grilled Chicken Panini',price:13,rating:4.9},{image:u('1539252554453-80ab65ce3586'),name:'Fresh Veggie Stack',price:11,rating:4.6},{image:u('1481070414801-51fd732d7184'),name:'Golden Tuna Melt',price:15,rating:4.8}],
  Asian:[
    {image:u('1569718212165-3a8278d5f624'),name:'Spicy Miso Ramen',price:17,rating:4.9},{image:u('1547592180-85f173990554'),name:'Teriyaki Bento',price:19,rating:4.7},{image:u('1579871494447-9811cf80d66c'),name:'Salmon Sushi',price:21,rating:4.9},{image:u('1563245372-f21724e3856d'),name:'Crispy Dumplings',price:13,rating:4.8},{image:u('1601050690597-df0568f70950'),name:'Coconut Curry',price:16,rating:4.8}],
  'Set Menu':[
    {image:u('1543353071-873f17a7a088'),name:'Family Feast',price:32,rating:4.9},{image:u('1498837167922-ddd27525d352'),name:'Healthy Lunch Combo',price:22,rating:4.8},{image:u('1543362906-acfc16c67564'),name:'Protein Power Box',price:24,rating:4.7},{image:u('1490645935967-10de6ba17061'),name:'Kids Favorite',price:17,rating:4.8},{image:u('1547592180-85f173990554'),name:'Weekend Special',price:29,rating:4.9}]
};
const restaurants=[
  {image:'assets/images/restaurant-1.jpg',name:'Blaze Pizza',hours:'11:00 AM – 10:00 PM',rating:'4.9',category:'Pizza'},
  {image:'assets/images/restaurant-2.jpg',name:'Pizza Ranch',hours:'09:00 AM – 10:00 PM',rating:'4.8',category:'Pizza'},
  {image:'assets/images/restaurant-3.jpg',name:"Dion’s Pizza House",hours:'10:00 AM – 12:00 AM',rating:'4.7',category:'Pizza'},
  {image:'assets/images/restaurant-4.jpg',name:'Royal Burger',hours:'11:00 AM – 10:00 PM',rating:'4.9',category:'Burger'},
  {image:'assets/images/restaurant-5.jpg',name:'Crispy Chicken Co.',hours:'09:00 AM – 10:00 PM',rating:'4.8',category:'Burger'},
  {image:'assets/images/restaurant-6.jpg',name:'Star Food Kitchen',hours:'10:00 AM – 12:00 AM',rating:'4.7',category:'Set Menu'}
];
const testimonials=[
  {text:'EFood has the best user experience. Ordering is effortless, delivery is always on time, and every courier I have met has been friendly and professional.',name:'Angelina Jolie',role:'Food lover',photo:'assets/images/testimonial-client.jpg'},
  {text:'A busy week used to mean compromising on dinner. Now I can discover excellent local restaurants and have a fresh meal at my door before my next meeting.',name:'Sophia Martin',role:'Product designer',photo:u('1494790108377-be9c29b29330')},
  {text:'The live updates are accurate and the selection is fantastic. EFood quickly became the only delivery service our whole family needs.',name:'Daniel Lee',role:'Regular customer',photo:u('1500648767791-00dcc994a43e')}
];
const categories=Object.keys(products); let allProducts=Object.entries(products).flatMap(([category,items])=>items.map(item=>({...item,category})));
let activeCategory='All',quoteIndex=0,cart=JSON.parse(localStorage.getItem('efood-cart')||'[]'),currentUser=null,accountOrders=[],recoveryId='',passwordChangeId='';
const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
const menuGrid=$('#menu-grid');
async function api(path,options={}){const response=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(data.error||'Request failed.'),{status:response.status,data});return data;}
function contentSet(selector,value,html=false){const element=$(selector);if(element&&value!==undefined)element[html?'innerHTML':'textContent']=value;}
function contentImage(selector,value){const image=$(selector);if(image&&value)image.src=value;}
function contentVisible(selector,value){const element=$(selector);if(element)element.hidden=value===false;}
function createNavigationLink(item){const link=document.createElement('a');link.textContent=item.label;link.href=item.href;return link;}
function reorderSectionsFromNavigation(items=[]){const main=$('main'),ordered=[],seen=new Set();if(!main)return;items.forEach(item=>{if(typeof item.href!=='string'||!item.href.startsWith('#'))return;const id=item.href.slice(1),section=document.getElementById(id);if(section&&section.parentElement===main&&!seen.has(section)){seen.add(section);ordered.push(section);}});ordered.reverse().forEach(section=>main.prepend(section));}
function renderCustomSections(sections=[]){$$('.cms-custom-section').forEach(section=>section.remove());const support=$('#support');sections.filter(section=>section.visible!==false).forEach((section,index)=>{const element=document.createElement('section');element.className=`section cms-custom-section${index%2?' alt':''}`;element.id=section.id;const container=document.createElement('div');container.className='container split-grid';const content=document.createElement('div');content.className='content-block reveal visible';if(section.eyebrow){const eyebrow=document.createElement('span');eyebrow.className='eyebrow';eyebrow.textContent=section.eyebrow;content.append(eyebrow);}const title=document.createElement('h2');title.textContent=section.title;content.append(title);if(section.description){const description=document.createElement('p');description.textContent=section.description;content.append(description);}if(section.buttonLabel){const button=document.createElement('a');button.className='btn btn-primary';button.textContent=section.buttonLabel;button.href=section.buttonHref||'#home';content.append(button);}const imageWrap=document.createElement('div');imageWrap.className='contactless-visual reference-photo reveal visible';if(section.image){const image=document.createElement('img');image.src=section.image;image.alt=section.title||'';imageWrap.append(image);}if(section.image&&index%2===0)container.append(imageWrap,content);else{container.append(content);if(section.image)container.append(imageWrap);}element.append(container);support?.parentNode.insertBefore(element,support);});}
async function loadNavigation(){try{const{content}=await api('/api/site'),items=content.navigation?.items||[];const navigation=$('.main-nav');navigation.replaceChildren(...items.map(createNavigationLink));const footerGroups=$$('.footer-grid>div:not(.brand-column)');if(footerGroups[0]){footerGroups[0].replaceChildren();const heading=document.createElement('h4');heading.textContent='Navigation';footerGroups[0].append(heading,...items.map(createNavigationLink));}footerGroups.slice(1).forEach(group=>group.hidden=true);const oldFooterLinks=$('.footer-bottom>div');if(oldFooterLinks)oldFooterLinks.hidden=true;renderCustomSections(content.customSections||[]);reorderSectionsFromNavigation(items);}catch(error){console.error('Navigation could not be loaded:',error.message);}}
async function loadSiteContent(){try{const{content:c}=await api('/api/site');document.title=c.general.pageTitle;document.querySelector('meta[name="description"]').content=c.general.metaDescription;$$('.logo').forEach(logo=>logo.innerHTML=`<span>${c.general.siteName.charAt(0)}</span>${c.general.siteName.slice(1)}`);contentVisible('.hero',c.hero.visible);contentSet('.hero-copy .eyebrow',c.hero.eyebrow);contentSet('.hero-copy h1',c.hero.title,true);contentSet('.hero-copy>p',c.hero.description);contentImage('.hero-visual img',c.hero.image);contentSet('.hero-copy .btn',c.hero.primaryButton);contentSet('.hero-copy .text-link',`${c.hero.secondaryButton} ↗`);contentSet('.hero-trust>span',c.hero.trust);contentVisible('#service',c.menu.visible);contentSet('#service .section-heading .eyebrow',c.menu.eyebrow);contentSet('#service .section-heading h2',c.menu.title,true);contentSet('#service .section-heading p',c.menu.description);contentVisible('#about',c.about.visible);contentSet('#about .eyebrow',c.about.eyebrow);contentSet('#about h2',c.about.title,true);contentSet('#about .content-block>p',c.about.description);contentImage('#about img',c.about.image);contentSet('#about .btn',`${c.about.button} →`);const featureTexts=c.about.features.split('\n').filter(Boolean);$$('#about .feature-list div span').forEach((span,index)=>{if(featureTexts[index])span.textContent=featureTexts[index]});contentVisible('#restaurants',c.restaurants.visible);contentSet('#restaurants .eyebrow',c.restaurants.eyebrow);contentSet('#restaurants h2',c.restaurants.title,true);contentSet('#restaurants .section-heading p',c.restaurants.description);contentVisible('#app',c.app.visible);contentSet('#app .eyebrow',c.app.eyebrow);contentSet('#app h2',c.app.title,true);contentSet('#app .content-block>p',c.app.description);contentImage('#app img',c.app.image);contentVisible('.testimonials',c.testimonials.visible);contentSet('.testimonials .eyebrow',c.testimonials.eyebrow);contentSet('.testimonials h2',c.testimonials.title,true);contentVisible('#support',c.support.visible);contentSet('#support .eyebrow',c.support.eyebrow);contentSet('#support h2',c.support.title,true);contentSet('#support .support-copy>p',c.support.description);const phoneLink=$('#support a[href^="tel:"]');if(phoneLink){phoneLink.textContent=c.support.phone;phoneLink.href=`tel:${c.support.phone.replace(/[^+\d]/g,'')}`;}const footerLines=$$('.brand-column>p');if(footerLines[0])footerLines[0].textContent=`📍 ${c.footer.address}`;if(footerLines[1])footerLines[1].textContent=`☎ ${c.footer.phone}`;if(footerLines[2])footerLines[2].textContent=`✉ ${c.footer.email}`;contentSet('.footer-bottom>span',c.footer.copyright);}catch(error){console.error('Site content could not be loaded:',error.message);}}
async function loadDynamicMenu(){try{const{dishes}=await api('/api/menu');if(dishes?.length){products={};for(const dish of dishes){if(!products[dish.category])products[dish.category]=[];products[dish.category].push(dish);}allProducts=Object.entries(products).flatMap(([category,items])=>items.map(item=>({...item,category})));renderMenu();}}catch(error){console.error('Dynamic menu could not be loaded:',error.message);}}
async function loadSession(){try{const data=await api('/api/account');currentUser=data.user;}catch{currentUser=null;}finally{document.body.classList.remove('auth-loading');updateAuthUI();const match=location.hash.match(/^#account\/(orders|details)$/);if(match&&currentUser)await showAccount(match[1],false);else if(match&&!currentUser){showSite(false);requireAuth();}else{const saved=Number(sessionStorage.getItem('efood-scroll')||0);if(!location.hash&&saved)requestAnimationFrame(()=>scrollTo(0,saved));}if(currentUser&&!currentUser.emailVerified)openVerifyEmail();}}
function productCard(item){return `<article class="menu-card"><div class="dish-photo"><img src="${item.image}" alt="${item.name}" loading="lazy"></div><div class="rating" aria-label="${item.rating} out of 5">★ ${item.rating}</div><h3>${item.name}</h3><div class="price">$${item.price.toFixed(2)}</div><button class="add-cart" data-name="${item.name}">Add to Cart</button></article>`;}
function getFilteredProducts(){return activeCategory==='All'?allProducts:products[activeCategory];}
function renderMenu(){menuGrid.innerHTML=getFilteredProducts().map(productCard).join('');}
function renderRestaurants(){$('#restaurant-grid').innerHTML=restaurants.map((r,i)=>`<article class="restaurant-card" tabindex="0" data-index="${i}"><div class="restaurant-photo"><img src="${r.image}" alt="Food from ${r.name}" loading="lazy"></div><div class="restaurant-info"><div><h3>${r.name}</h3><p>◷ &nbsp;${r.hours} · ★ ${r.rating}</p></div><button class="arrow-btn" aria-label="View ${r.name}">→</button></div></article>`).join('');}
function showToast(text){const toast=$('.toast');toast.textContent=text;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2200);}
function setCategory(category){activeCategory=category;$$('.category-tab').forEach(tab=>{const on=tab.dataset.category===category;tab.classList.toggle('active',on);tab.setAttribute('aria-selected',on)});animateMenu();}
function animateMenu(){menuGrid.classList.remove('slide-in');void menuGrid.offsetWidth;menuGrid.classList.add('slide-in');renderMenu();}
function saveCart(){localStorage.setItem('efood-cart',JSON.stringify(cart));renderCart();}
function isAuthenticated(){return Boolean(currentUser);}
function requireAuth(){if(!isAuthenticated()){closeCart();closeModal();openModal('.sign-up-modal');$('.form-error',$('#signup-form')).textContent='Create an account to order food.';return false;}if(!currentUser.emailVerified){closeCart();closeModal();openVerifyEmail();showToast('Verify your email to continue.');return false;}return true;}
function addToCart(name){if(!requireAuth())return false;const product=allProducts.find(p=>p.name===name);const existing=cart.find(item=>item.name===name);if(existing)existing.qty++;else cart.push({...product,qty:1});saveCart();showToast(`${name} added to your cart`);return true;}
function renderCart(){const count=cart.reduce((sum,item)=>sum+item.qty,0);$('.cart-count').textContent=count;$('.cart-items').innerHTML=cart.map(item=>`<div class="cart-item"><img src="${item.image}" alt=""><div><strong>${item.name}</strong><small>$${item.price.toFixed(2)}</small><div class="qty"><button data-action="minus" data-name="${item.name}" aria-label="Decrease quantity">−</button><span>${item.qty}</span><button data-action="plus" data-name="${item.name}" aria-label="Increase quantity">+</button></div></div><button class="remove-item" data-action="remove" data-name="${item.name}" aria-label="Remove ${item.name}">×</button></div>`).join('');$('.cart-empty').hidden=cart.length>0;$('.cart-summary').hidden=cart.length===0;$('.cart-subtotal').textContent=`$${cart.reduce((sum,item)=>sum+item.price*item.qty,0).toFixed(2)}`;}
function openCart(){closeModal();$('.cart-drawer').classList.add('open');$('.cart-drawer').setAttribute('aria-hidden','false');$('.overlay').hidden=false;document.body.classList.add('no-scroll');$('.drawer-close').focus();}
function closeCart(){$('.cart-drawer').classList.remove('open');$('.cart-drawer').setAttribute('aria-hidden','true');if(!$('.modal:not([hidden])')){$('.overlay').hidden=true;document.body.classList.remove('no-scroll');}}
function openModal(selector){closeCart();const modal=$(selector);modal.hidden=false;$('.overlay').hidden=false;document.body.classList.add('no-scroll');setTimeout(()=>modal.classList.add('open'),10);const focusable=$('input,button',modal);if(focusable)focusable.focus();}
function closeModal(){const modal=$('.modal:not([hidden])');if(!modal)return;modal.classList.remove('open');modal.hidden=true;$('.overlay').hidden=true;document.body.classList.remove('no-scroll');}

function clearErrors(form){$$('.field-error',form).forEach(el=>el.textContent='');$$('input',form).forEach(el=>el.classList.remove('invalid'));const general=$('.form-error',form);if(general)general.textContent='';}
function fieldError(input,message){input.classList.add('invalid');const error=input.closest('label')?.querySelector('.field-error');if(error)error.textContent=message;return false;}
function updateAuthUI(){const session=currentUser;$('.sign-in').hidden=Boolean(session);$('.sign-up').hidden=Boolean(session);$('.user-menu').hidden=!session;if(session){$('.user-name').textContent=session.name.split(' ')[0];$('.user-avatar').textContent=session.name.charAt(0).toUpperCase();}else if(document.body.classList.contains('account-view'))showSite(false);}
function switchAuth(type){closeModal();openModal(type==='signin'?'.sign-in-modal':'.sign-up-modal');}
function showFood(name){const item=allProducts.find(product=>product.name===name);if(!item)return;$('.food-modal-image').src=item.image;$('.food-modal-image').alt=item.name;$('#food-title').textContent=item.name;$('.food-modal-category').textContent=item.category;$('.food-modal-rating').textContent=`★ ${item.rating} rating`;$('.food-modal-price').textContent=`$${item.price.toFixed(2)}`;$('.food-modal-cart').dataset.name=item.name;closeModal();openModal('.food-modal');}
function openVerifyEmail(){if(!currentUser)return;const form=$('#verify-email-form');form.reset();clearErrors(form);$('.verification-email').textContent=currentUser.email;$('.verification-dev-code').hidden=true;$('.verification-dev-code').textContent='';openModal('.verify-email-modal');setTimeout(()=>form.elements.code.focus(),50);}
function renderAccount(){const user=currentUser,orders=accountOrders;if(!user)return;$('.account-avatar').textContent=user.name.charAt(0).toUpperCase();$('.account-name').textContent=user.name;$('.account-email').textContent=user.email;$('.profile-name').value=user.name;$('.profile-email').value=user.email;$('.profile-phone').value=user.phone;$('.profile-address').value=user.address||'';$('.email-verified-badge').hidden=!user.emailVerified;$('.email-unverified-badge').hidden=user.emailVerified;$('.order-history').innerHTML=orders.length?orders.map(order=>`<article class="history-card"><div class="history-top"><div><strong>Order #${order.number}</strong><small>${new Intl.DateTimeFormat('en',{dateStyle:'medium',timeStyle:'short'}).format(new Date(order.createdAt))}</small></div><span>${order.status}</span></div><div class="history-items">${order.items.map(item=>`<div><img src="${item.image}" alt=""><span>${item.qty} × ${item.name}</span></div>`).join('')}</div><div class="history-total"><span>${order.items.reduce((sum,item)=>sum+item.qty,0)} items · ${order.address}</span><strong>$${order.total.toFixed(2)}</strong></div></article>`).join(''):'<div class="empty-history"><span>🧾</span><h3>No orders yet</h3><p>Your completed orders will appear here.</p><button class="btn btn-primary account-order-more" type="button">Explore menu</button></div>';}
async function showAccount(panel='orders',updateUrl=true){if(!currentUser)return requireAuth();if(updateUrl&&!document.body.classList.contains('account-view'))sessionStorage.setItem('efood-scroll',String(scrollY));try{accountOrders=(await api('/api/orders')).orders;}catch(error){showToast(error.message);return;}renderAccount();$$('.profile-details input').forEach(input=>{input.readOnly=true;input.classList.remove('invalid')});$$('.profile-field-error').forEach(error=>error.textContent='');$('.profile-edit').hidden=false;$('.profile-save').hidden=true;document.body.classList.add('account-view');$('.account-page').hidden=false;selectAccountPanel(panel,false);if(updateUrl)history.pushState({view:'account',panel},'',`#account/${panel}`);window.scrollTo({top:0,behavior:updateUrl?'smooth':'auto'});}
function showSite(updateUrl=true){document.body.classList.remove('account-view');$('.account-page').hidden=true;if(updateUrl)history.pushState({view:'site'},'','#home');}

$$('.category-tab').forEach(tab=>tab.addEventListener('click',()=>setCategory(tab.dataset.category)));
menuGrid.addEventListener('click',e=>{const card=e.target.closest('.menu-card');if(!card)return;if(!isAuthenticated()){requireAuth();return;}const button=e.target.closest('.add-cart');if(!button)return;if(addToCart(button.dataset.name)){button.textContent='Added ✓';setTimeout(()=>button.textContent='Add to Cart',900);}});
function renderQuote(){const q=testimonials[quoteIndex],panel=$('.quote-panel');panel.classList.remove('slide-in');void panel.offsetWidth;panel.classList.add('slide-in');$('#quote-text').textContent=q.text;$('#quote-name').textContent=q.name;$('#quote-role').textContent=q.role;$('#quote-position').textContent=`${quoteIndex+1} / ${testimonials.length}`;$('#quote-photo').src=q.photo;$('#quote-photo').alt=`${q.name}, ${q.role}`;}
$('#quote-next').addEventListener('click',()=>{quoteIndex=(quoteIndex+1)%testimonials.length;renderQuote();});$('#quote-prev').addEventListener('click',()=>{quoteIndex=(quoteIndex-1+testimonials.length)%testimonials.length;renderQuote();});
const toggle=$('.menu-toggle'),nav=$('.main-nav');toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open);});nav.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');});
$('#feedback-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form),status=$('.feedback-message'),button=$('button[type="submit"]',form),payload={topic:data.get('topic'),message:data.get('message').trim()};status.textContent='';if(payload.message.length<10){status.textContent='Please describe your question in more detail.';return;}button.disabled=true;try{const result=await api('/api/feedback',{method:'POST',body:JSON.stringify(payload)});status.textContent=`✓ ${result.message} Reference #${result.reference}`;form.elements.message.value='';}catch(error){status.textContent=error.message;}finally{button.disabled=false;}});
$('.cart-button').addEventListener('click',openCart);$('.drawer-close').addEventListener('click',closeCart);$('.overlay').addEventListener('click',()=>{closeCart();closeModal();});
$('.cart-items').addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(!btn)return;const item=cart.find(x=>x.name===btn.dataset.name);if(btn.dataset.action==='plus')item.qty++;if(btn.dataset.action==='minus')item.qty--;if(btn.dataset.action==='remove'||item.qty<1)cart=cart.filter(x=>x.name!==btn.dataset.name);saveCart();});
$('.search-button').addEventListener('click',()=>{openModal('.search-modal');$('.search-input').value='';$('.search-results').innerHTML='<p class="search-hint">Search across all 25 dishes.</p>';});
$('.search-input').addEventListener('input',e=>{const query=e.target.value.trim().toLowerCase();const found=query?allProducts.filter(p=>`${p.name} ${p.category}`.toLowerCase().includes(query)):[];$('.search-results').innerHTML=query?(found.length?found.map(p=>`<button class="search-result" data-name="${p.name}"><img src="${p.image}" alt=""><span><strong>${p.name}</strong><small>${p.category} · $${p.price.toFixed(2)}</small></span><b>→</b></button>`).join(''):'<p class="search-hint">No dishes found. Try another name.</p>'):'<p class="search-hint">Search across all 25 dishes.</p>';});
$('.search-results').addEventListener('click',e=>{const result=e.target.closest('.search-result');if(!result)return;if(!requireAuth())return;showFood(result.dataset.name);});
function showRestaurant(index){const r=restaurants[index];$('.restaurant-modal-image').src=r.image;$('.restaurant-modal-image').alt=`Food from ${r.name}`;$('#restaurant-title').textContent=r.name;$('.restaurant-modal-meta').textContent=`★ ${r.rating} · ${r.hours}`;$('.restaurant-order').dataset.category=r.category;openModal('.restaurant-modal');}
$('#restaurant-grid').addEventListener('click',e=>{const card=e.target.closest('.restaurant-card');if(!card)return;if(!requireAuth())return;showRestaurant(Number(card.dataset.index));});$('#restaurant-grid').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.restaurant-card')){if(!requireAuth())return;showRestaurant(Number(e.target.dataset.index));}});
$('.restaurant-order').addEventListener('click',e=>{const category=e.currentTarget.dataset.category;closeModal();setCategory(category);$('#service').scrollIntoView({behavior:'smooth'});});
$('.checkout-button').addEventListener('click',()=>{if(!requireAuth())return;const user=currentUser,form=$('#checkout-form');$$('.checkout-identity').forEach(label=>label.hidden=true);form.elements.name.required=true;form.elements.phone.required=true;form.elements.name.value=user.name;form.elements.phone.value=user.phone;form.elements.address.value=user.address||'';$('.checkout-eyebrow').textContent='Quick checkout';$('.checkout-user-note').textContent=`Recipient: ${user.name} · ${user.phone}`;$('.checkout-user-note').hidden=false;$('.edit-recipient').hidden=false;$('.edit-recipient').textContent='Change recipient details';openModal('.checkout-modal');});
$('.edit-recipient').addEventListener('click',e=>{const fields=$$('.checkout-identity'),willOpen=fields.some(field=>field.hidden);fields.forEach(field=>field.hidden=!willOpen);e.currentTarget.textContent=willOpen?'Use saved recipient':'Change recipient details';if(willOpen)$('#checkout-form').elements.name.focus();});
$('#checkout-form').addEventListener('submit',async e=>{e.preventDefault();if(!requireAuth()||!e.currentTarget.reportValidity())return;const form=e.currentTarget,data=new FormData(form),button=$('button[type="submit"]',form);button.disabled=true;try{await api('/api/orders',{method:'POST',body:JSON.stringify({recipient:data.get('name'),phone:data.get('phone'),address:data.get('address'),items:cart})});cart=[];saveCart();closeModal();form.reset();showToast('Order placed! We will call you to confirm.');}catch(error){showToast(error.message);if(error.status===401){currentUser=null;updateAuthUI();requireAuth();}}finally{button.disabled=false;}});
$$('.modal-close').forEach(btn=>btn.addEventListener('click',closeModal));
$$('.app-download').forEach(btn=>btn.addEventListener('click',()=>showToast(`${btn.dataset.store} version is coming soon — you’re on the waitlist!`)));
$('.sign-up').addEventListener('click',()=>openModal('.sign-up-modal'));$('.sign-in').addEventListener('click',()=>openModal('.sign-in-modal'));
$$('[data-auth-switch]').forEach(button=>button.addEventListener('click',()=>switchAuth(button.dataset.authSwitch)));
$$('.password-toggle').forEach(button=>button.addEventListener('click',()=>{const input=$('input',button.parentElement);const show=input.type==='password';input.type=show?'text':'password';button.textContent=show?'Hide':'Show';button.setAttribute('aria-label',show?'Hide password':'Show password');}));
$('#signup-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form),name=data.get('name').trim(),email=data.get('email').trim().toLowerCase(),phone=data.get('phone').trim(),address=data.get('address').trim(),password=data.get('password'),confirm=data.get('confirm');clearErrors(form);let valid=true;if(name.length<2)valid=fieldError(form.elements.name,'Enter at least 2 characters.')&&valid;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))valid=fieldError(form.elements.email,'Enter a valid email address.')&&valid;if(!/^\+?[\d\s()-]{7,20}$/.test(phone))valid=fieldError(form.elements.phone,'Enter a valid phone number.')&&valid;if(address.length<6)valid=fieldError(form.elements.address,'Enter your full delivery address.')&&valid;if(password.length<8||!/[A-Za-z]/.test(password)||!/\d/.test(password))valid=fieldError(form.elements.password,'Use 8+ characters with a letter and number.')&&valid;if(confirm!==password)valid=fieldError(form.elements.confirm,'Passwords do not match.')&&valid;if(!form.elements.terms.checked){$('.form-error',form).textContent='Please accept the Terms and Privacy Policy.';valid=false;}if(!valid)return;try{const result=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name,email,phone,address,password})});currentUser=result.user;form.reset();closeModal();updateAuthUI();if(result.requiresVerification){openVerifyEmail(result.devCode);showToast('Account created. Verify your email to continue.');}else showToast('Account created successfully.');}catch(error){$('.form-error',form).textContent=error.message;Object.entries(error.data?.fields||{}).forEach(([key,message])=>form.elements[key]&&fieldError(form.elements[key],message));}});
$('#signin-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form),email=data.get('email').trim().toLowerCase(),password=data.get('password');clearErrors(form);let valid=true;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))valid=fieldError(form.elements.email,'Enter a valid email address.')&&valid;if(!password)valid=fieldError(form.elements.password,'Enter your password.')&&valid;if(!valid)return;try{const result=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})});currentUser=result.user;form.reset();closeModal();updateAuthUI();if(!currentUser.emailVerified)openVerifyEmail();else showToast(`Welcome back, ${currentUser.name.split(' ')[0]}!`);}catch(error){$('.form-error',form).textContent=error.message;}});
$('.user-menu').addEventListener('click',()=>showAccount());$('.account-home').addEventListener('click',()=>showSite());$('.account-logout').addEventListener('click',async()=>{try{await api('/api/auth/logout',{method:'POST'});}catch{}currentUser=null;showSite();updateAuthUI();showToast('You have signed out.');});
function selectAccountPanel(name,updateUrl=true){$$('[data-account-panel]').forEach(item=>item.classList.toggle('active',item.dataset.accountPanel===name));$$('.account-panel').forEach(panel=>panel.hidden=panel.dataset.panel!==name);if(updateUrl&&document.body.classList.contains('account-view'))history.replaceState({view:'account',panel:name},'',`#account/${name}`);}
$$('.account-sidebar,.account-nav').forEach(nav=>nav.addEventListener('click',e=>{const tab=e.target.closest('[data-account-panel]');if(tab)selectAccountPanel(tab.dataset.accountPanel);}));
$('.account-content').addEventListener('click',e=>{if(e.target.closest('.account-order-more')){showSite();setCategory('All');$('#service').scrollIntoView({behavior:'smooth'});}});
$('.profile-edit').addEventListener('click',()=>{$$('.profile-details input').forEach(input=>input.readOnly=false);$('.profile-edit').hidden=true;$('.profile-save').hidden=false;$('.profile-name').focus();});
$('.profile-save').addEventListener('click',async()=>{const form=$('.profile-details'),name=form.elements.name.value.trim(),email=form.elements.email.value.trim().toLowerCase(),phone=form.elements.phone.value.trim(),address=form.elements.address.value.trim();$$('.profile-field-error',form).forEach(error=>error.textContent='');$$('input',form).forEach(input=>input.classList.remove('invalid'));let valid=true;const error=(input,message)=>{input.classList.add('invalid');input.parentElement.querySelector('.profile-field-error').textContent=message;valid=false;};if(name.length<2)error(form.elements.name,'Enter at least 2 characters.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))error(form.elements.email,'Enter a valid email.');if(!/^\+?[\d\s()-]{7,20}$/.test(phone))error(form.elements.phone,'Enter a valid phone number.');if(address.length<6)error(form.elements.address,'Enter your full address.');if(!valid)return;try{const result=await api('/api/account',{method:'PUT',body:JSON.stringify({name,email,phone,address})});currentUser=result.user;$$('.profile-details input').forEach(input=>input.readOnly=true);$('.profile-save').hidden=true;$('.profile-edit').hidden=false;renderAccount();updateAuthUI();if(result.requiresVerification)openVerifyEmail(result.devCode);else showToast('Personal details saved.');}catch(requestError){showToast(requestError.message);Object.entries(requestError.data?.fields||{}).forEach(([key,message])=>form.elements[key]&&error(form.elements[key],message));}});
function openRecovery(){const user=currentUser||{},form=$('#recovery-form'),maskEmail=value=>{const [name='',domain='']=value.split('@');return `${name.slice(0,2)}***@${domain}`;},maskPhone=value=>`${value.slice(0,3)} *** ${value.slice(-3)}`;form.reset();clearErrors(form);form.elements.identifier.value=user.email||$('#signin-form').elements.email.value||'';$('.recovery-confirm').hidden=true;$('.send-code').hidden=false;$('.recovery-email').textContent=user.email?maskEmail(user.email):'Registered email';$('.recovery-phone').textContent=user.phone?maskPhone(user.phone):'Registered phone';recoveryId='';openModal('.recovery-modal');}
$('.change-password-open').addEventListener('click',()=>{const form=$('#password-form');form.reset();clearErrors(form);$('.password-request-fields').hidden=false;$('.password-email-confirm').hidden=true;passwordChangeId='';openModal('.password-modal');});$('.forgot-password-open').addEventListener('click',openRecovery);$('.signin-forgot').addEventListener('click',()=>{closeModal();openRecovery();});$('.forgot-from-password').addEventListener('click',()=>{closeModal();openRecovery();});
$('#password-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form),current=data.get('current'),password=data.get('password'),confirm=data.get('confirm');clearErrors(form);let valid=true;if(!current)valid=fieldError(form.elements.current,'Enter your current password.')&&valid;if(password.length<8||!/[A-Za-z]/.test(password)||!/\d/.test(password))valid=fieldError(form.elements.password,'Use 8+ characters with a letter and number.')&&valid;if(password!==confirm)valid=fieldError(form.elements.confirm,'Passwords do not match.')&&valid;if(!valid)return;try{const result=await api('/api/auth/change-password',{method:'POST',body:JSON.stringify({currentPassword:current,password})});passwordChangeId=result.changeId;$('.password-request-fields').hidden=true;$('.password-email-confirm').hidden=false;$('.password-code-notice').textContent=`${result.message}${result.devCode?` Development code: ${result.devCode}`:''}`;form.elements.code.focus();}catch(error){$('.form-error',$('.password-request-fields')).textContent=error.message;Object.entries(error.data?.fields||{}).forEach(([key,message])=>form.elements[key]&&fieldError(form.elements[key],message));}});
$('.confirm-password-change').addEventListener('click',async()=>{const form=$('#password-form'),code=form.elements.code.value.trim();clearErrors($('.password-email-confirm'));if(!/^\d{6}$/.test(code)){fieldError(form.elements.code,'Enter the 6-digit code.');return;}try{const result=await api('/api/auth/change-password/confirm',{method:'POST',body:JSON.stringify({changeId:passwordChangeId,code})});currentUser=result.user;passwordChangeId='';form.reset();closeModal();updateAuthUI();showToast('Password changed successfully.');}catch(error){$('.form-error',$('.password-email-confirm')).textContent=error.message;Object.entries(error.data?.fields||{}).forEach(([key,message])=>form.elements[key]&&fieldError(form.elements[key],message));}});
$('.restart-password-change').addEventListener('click',()=>{const form=$('#password-form');clearErrors(form);form.elements.code.value='';passwordChangeId='';$('.password-email-confirm').hidden=true;$('.password-request-fields').hidden=false;form.elements.current.focus();});
$('.send-code').addEventListener('click',async()=>{const form=$('#recovery-form'),data=new FormData(form),channel=data.get('channel'),identifier=data.get('identifier').trim().toLowerCase(),button=$('.send-code');clearErrors(form);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(identifier)){fieldError(form.elements.identifier,'Enter your registered email.');return;}button.disabled=true;try{const result=await api('/api/auth/recovery/request',{method:'POST',body:JSON.stringify({channel,identifier})});recoveryId=result.recoveryId;$('.recovery-confirm').hidden=false;button.hidden=true;$('.code-notice').textContent=`${result.message}${result.devCode?` Development code: ${result.devCode}`:''}`;form.elements.code.focus();}catch(error){showToast(error.message);}finally{button.disabled=false;}});
$('#recovery-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form),code=data.get('code').trim(),password=data.get('password'),confirm=data.get('confirm');clearErrors(form);let valid=true;if(!/^\d{6}$/.test(code))valid=fieldError(form.elements.code,'Enter the 6-digit code.')&&valid;if(password.length<8||!/[A-Za-z]/.test(password)||!/\d/.test(password))valid=fieldError(form.elements.password,'Use 8+ characters with a letter and number.')&&valid;if(password!==confirm)valid=fieldError(form.elements.confirm,'Passwords do not match.')&&valid;if(!valid)return;try{const result=await api('/api/auth/recovery/confirm',{method:'POST',body:JSON.stringify({recoveryId,code,password})});currentUser=result.user;recoveryId='';form.reset();closeModal();updateAuthUI();showToast('Password reset successfully.');}catch(error){$('.form-error',form).textContent=error.message;Object.entries(error.data?.fields||{}).forEach(([key,message])=>form.elements[key]&&fieldError(form.elements[key],message));}});
$('#verify-email-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,code=form.elements.code.value.trim();clearErrors(form);if(!/^\d{6}$/.test(code)){fieldError(form.elements.code,'Enter the 6-digit code.');return;}try{currentUser=(await api('/api/auth/verify-email',{method:'POST',body:JSON.stringify({code})})).user;form.reset();closeModal();updateAuthUI();if(document.body.classList.contains('account-view'))renderAccount();showToast('Email verified successfully. You can now order.');}catch(error){$('.form-error',form).textContent=error.message;Object.entries(error.data?.fields||{}).forEach(([key,message])=>form.elements[key]&&fieldError(form.elements[key],message));}});
$('.resend-verification').addEventListener('click',async e=>{const button=e.currentTarget;button.disabled=true;try{const result=await api('/api/auth/resend-verification',{method:'POST',body:'{}'});$('.verification-dev-code').hidden=true;$('.verification-dev-code').textContent='';showToast(`${result.message} Check your inbox.`);}catch(error){showToast(error.message);}finally{button.disabled=false;}});
$('.email-unverified-badge').addEventListener('click',openVerifyEmail);
$('.main-nav').addEventListener('click',e=>{if(document.body.classList.contains('account-view')&&e.target.closest('a'))showSite();});
$('.food-modal-cart').addEventListener('click',e=>{if(!addToCart(e.currentTarget.dataset.name))return;closeModal();openCart();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeCart();closeModal();}});
history.scrollRestoration='manual';window.addEventListener('pagehide',()=>{if(!document.body.classList.contains('account-view'))sessionStorage.setItem('efood-scroll',String(scrollY));});window.addEventListener('popstate',async()=>{const match=location.hash.match(/^#account\/(orders|details)$/);if(match&&currentUser)await showAccount(match[1],false);else{showSite(false);const target=location.hash&&$(location.hash);if(target)target.scrollIntoView();else scrollTo(0,Number(sessionStorage.getItem('efood-scroll')||0));}});
window.addEventListener('scroll',()=>{$('.site-header').classList.toggle('scrolled',scrollY>12);let current='home';$$('main section[id], footer[id]').forEach(section=>{if(section.offsetTop<=scrollY+140)current=section.id;});$$('.main-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${current}`));},{passive:true});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));
renderMenu();renderRestaurants();renderQuote();renderCart();loadSiteContent();loadNavigation();loadDynamicMenu();loadSession();
